In [178]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score

In [147]:
games = pd.read_csv('games_data.csv', index_col=0)

In [148]:
games.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,...,Match Report,NaN,13.0,1.0,18.7,1.0,1,1,2022,Manchester City
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,Match Report,NaN,19.0,7.0,17.5,0.0,0,0,2022,Manchester City
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,Match Report,NaN,21.0,10.0,16.2,1.0,0,0,2022,Manchester City
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,Match Report,NaN,18.0,5.0,14.1,0.0,0,0,2022,Manchester City
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,Match Report,NaN,17.0,9.0,14.8,0.0,0,0,2022,Manchester City

In [149]:
games.shape

(2166, 27)

In [150]:
games.info

<bound method DataFrame.info of           date   time            comp         round  day venue result  gf  ga  \
1   2022-08-07  16:30  Premier League   Matchweek 1  Sun  Away      W   2   0
2   2022-08-13  15:00  Premier League   Matchweek 2  Sat  Home      W   4   0
3   2022-08-21  16:30  Premier League   Matchweek 3  Sun  Away      D   3   3
4   2022-08-27  15:00  Premier League   Matchweek 4  Sat  Home      W   4   2
5   2022-08-31  19:30  Premier League   Matchweek 5  Wed  Home      W   6   0
..         ...    ...             ...           ...  ...   ...    ...  ..  ..
38  2021-05-02  19:15  Premier League  Matchweek 34  Sun  Away      L   0   4
39  2021-05-08  15:00  Premier League  Matchweek 35  Sat  Home      L   0   2
40  2021-05-16  19:00  Premier League  Matchweek 36  Sun  Away      W   1   0
41  2021-05-19  18:00  Premier League  Matchweek 37  Wed  Away      L   0   1
42  2021-05-23  16:00  Premier League  Matchweek 38  Sun  Home      W   1   0

           opponent  ...  match report  notes    sh   sot  dist   fk pk pkatt  \
1          West Ham  ...  Match Report    NaN  13.0   1.0  18.7  1.0  1     1
2       Bournemouth  ...  Match Report    NaN  19.0   7.0  17.5  0.0  0     0
3     Newcastle Utd  ...  Match Report    NaN  21.0  10.0  16.2  1.0  0     0
4    Crystal Palace  ...  Match Report    NaN  18.0   5.0  14.1  0.0  0     0
5   Nott'ham Forest  ...  Match Report    NaN  17.0   9.0  14.8  0.0  0     0
..              ...  ...           ...    ...   ...   ...   ...  ... ..   ...
38        Tottenham  ...  Match Report    NaN   8.0   1.0  18.2  0.0  0     0
39   Crystal Palace  ...  Match Report    NaN   7.0   0.0  13.4  1.0  0     0
40          Everton  ...  Match Report    NaN  10.0   3.0  18.5  0.0  0     0
41    Newcastle Utd  ...  Match Report    NaN  11.0   1.0  18.3  1.0  0     0
42          Burnley  ...  Match Report    NaN  12.0   3.0  17.4  0.0  0     0

    season              team
1     2022   Manchester City
2     2022   Manchester City
3     2022   Manchester City
4     2022   Manchester City
5     2022   Manchester City
..     ...               ...
38    2021  Sheffield United
39    2021  Sheffield United
40    2021  Sheffield United
41    2021  Sheffield United
42    2021  Sheffield United

[2166 rows x 27 columns]>


#checking missing value

In [151]:
# know how many games we have for each team
games['team'].value_counts()

Manchester City             114
Tottenham Hotspur           114
Everton                     114
West Ham United             114
Arsenal                     114
Chelsea                     114
Crystal Palace              114
Wolverhampton Wanderers     114
Manchester United           114
Aston Villa                 114
Brighton and Hove Albion    114
Liverpool                   114
Newcastle United            114
Leicester City               76
Burnley                      76
Leeds United                 76
Southampton                  76
Brentford                    76
Fulham                       76
Nottingham Forest            38
Bournemouth                  38
Watford                      38
Norwich City                 38
West Bromwich Albion         38
Sheffield United             38
Name: team, dtype: int64

In [152]:
games['round'].value_counts()

Matchweek 1     57
Matchweek 30    57
Matchweek 23    57
Matchweek 12    57
Matchweek 24    57
Matchweek 25    57
Matchweek 26    57
Matchweek 27    57
Matchweek 29    57
Matchweek 31    57
Matchweek 2     57
Matchweek 33    57
Matchweek 34    57
Matchweek 28    57
Matchweek 35    57
Matchweek 36    57
Matchweek 37    57
Matchweek 32    57
Matchweek 22    57
Matchweek 21    57
Matchweek 7     57
Matchweek 20    57
Matchweek 3     57
Matchweek 4     57
Matchweek 5     57
Matchweek 6     57
Matchweek 8     57
Matchweek 9     57
Matchweek 10    57
Matchweek 11    57
Matchweek 13    57
Matchweek 14    57
Matchweek 15    57
Matchweek 16    57
Matchweek 17    57
Matchweek 18    57
Matchweek 19    57
Matchweek 38    57
Name: round, dtype: int64

In [153]:
games[games['team'] == 'Liverpool']

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2022-08-06,12:30,Premier League,Matchweek 1,Sat,Away,D,2,2,Fulham,...,Match Report,NaN,11.0,3.0,12.4,0.0,0,0,2022,Liverpool
2,2022-08-15,20:00,Premier League,Matchweek 2,Mon,Home,D,1,1,Crystal Palace,...,Match Report,NaN,24.0,4.0,17.4,0.0,0,0,2022,Liverpool
3,2022-08-22,20:00,Premier League,Matchweek 3,Mon,Away,L,1,2,Manchester Utd,...,Match Report,NaN,17.0,5.0,14.4,0.0,0,0,2022,Liverpool
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,9,0,Bournemouth,...,Match Report,NaN,19.0,12.0,11.6,0.0,0,0,2022,Liverpool
5,2022-08-31,20:00,Premier League,Matchweek 5,Wed,Home,W,2,1,Newcastle Utd,...,Match Report,NaN,23.0,6.0,17.8,0.0,0,0,2022,Liverpool
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,2021-05-08,20:15,Premier League,Matchweek 35,Sat,Home,W,2,0,Southampton,...,Match Report,NaN,14.0,6.0,13.6,0.0,0,0,2021,Liverpool
49,2021-05-13,20:15,Premier League,Matchweek 34,Thu,Away,W,4,2,Manchester Utd,...,Match Report,NaN,17.0,8.0,14.9,0.0,0,0,2021,Liverpool
50,2021-05-16,16:30,Premier League,Matchweek 36,Sun,Away,W,2,1,West Brom,...,Match Report,NaN,26.0,6.0,18.3,1.0,0,0,2021,Liverpool
51,2021-05-19,20:15,Premier League,Matchweek 37,Wed,Away,W,3,0,Burnley,...,Match Report,NaN,20.0,3.0,16.2,1.0,0,0,2021,Liverpool
52,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,2,0,Crystal Palace,...,Match Report,NaN,19.0,5.0,14.7,1.0,0,0,2021,Liverpool

# Cleaning Data

In [154]:
games.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf                int64
ga                int64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk                int64
pkatt             int64
season            int64
team             object
dtype: object

In [155]:
# convert a date into numerical value
games['date'] = pd.to_datetime(games['date'])

In [156]:
games

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,...,Match Report,NaN,13.0,1.0,18.7,1.0,1,1,2022,Manchester City
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,Match Report,NaN,19.0,7.0,17.5,0.0,0,0,2022,Manchester City
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,Match Report,NaN,21.0,10.0,16.2,1.0,0,0,2022,Manchester City
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,Match Report,NaN,18.0,5.0,14.1,0.0,0,0,2022,Manchester City
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,Match Report,NaN,17.0,9.0,14.8,0.0,0,0,2022,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0,4,Tottenham,...,Match Report,NaN,8.0,1.0,18.2,0.0,0,0,2021,Sheffield United
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0,2,Crystal Palace,...,Match Report,NaN,7.0,0.0,13.4,1.0,0,0,2021,Sheffield United
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1,0,Everton,...,Match Report,NaN,10.0,3.0,18.5,0.0,0,0,2021,Sheffield United
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0,1,Newcastle Utd,...,Match Report,NaN,11.0,1.0,18.3,1.0,0,0,2021,Sheffield United
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1,0,Burnley,...,Match Report,NaN,12.0,3.0,17.4,0.0,0,0,2021,Sheffield United

In [157]:
games.dtypes

date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                       int64
ga                       int64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                       int64
pkatt                    int64
season                   int64
team                    object
dtype: object

In [158]:
# convert "venue" coulmn into numerical value
# convert from string to categories then to numbers
games['venue_num'] = games['venue'].astype('category').cat.codes

In [159]:
games['opponent_num'] = games['opponent'].astype('category').cat.codes

In [160]:
# ading time_hour column which get rid of mins then convert it into intger
games['time_hour'] = games['time'].str.replace(':.+', '', regex=True).astype('int')

In [161]:
games['day_num'] = games['date'].dt.day_of_week

In [162]:
games['target'] = (games['result'] == 'W').astype('int')

In [163]:
games

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_num,opponent_num,time_hour,day_num,target
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,...,1.0,1,1,2022,Manchester City,0,23,16,6,1
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,0.0,0,0,2022,Manchester City,1,2,15,5,1
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,1.0,0,0,2022,Manchester City,0,15,16,6,0
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,0.0,0,0,2022,Manchester City,1,7,15,5,1
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,0.0,0,0,2022,Manchester City,1,17,19,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0,4,Tottenham,...,0.0,0,0,2021,Sheffield United,0,20,19,6,0
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0,2,Crystal Palace,...,1.0,0,0,2021,Sheffield United,1,7,15,5,0
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1,0,Everton,...,0.0,0,0,2021,Sheffield United,0,8,19,6,1
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0,1,Newcastle Utd,...,1.0,0,0,2021,Sheffield United,0,15,18,2,0
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1,0,Burnley,...,0.0,0,0,2021,Sheffield United,1,5,16,6,1

In [164]:
games.dtypes

date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                       int64
ga                       int64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                       int64
pkatt                    int64
season                   int64
team                    object
venue_num                 int8
opponent_num              int8
time_hour                int32
day_num                  int64
target                   int32
dtype: object

# ML Models

In [165]:
rfc = RFC(n_estimators=50, min_samples_split=10, random_state=1)

In [166]:
train = games[games['date'] < '2022-01-01']

In [167]:
test = games[games['date'] > '2022-01-01']

In [168]:
predictors = ['venue_num', 'opponent_num', 'time_hour', 'day_num']

In [169]:
rfc.fit(train[predictors], train['target'])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [170]:
preds = rfc.predict(test[predictors])

In [173]:
acc = accuracy_score(test['target'], preds)

In [174]:
acc

0.5889748549323017

### dig dipper

In [175]:
combined = pd.DataFrame(dict(actual=test['target'], prediction=preds))

In [176]:
pd.crosstab(index=combined['actual'], columns=combined['prediction'])

prediction    0    1
actual
0           487  121
1           304  122

As we can see above the model prediction was good in losess cases (0) but we care about is the win so gonna try diffrent method

In [179]:
precision_score(test['target'], preds)

0.5020576131687243

### improving precision

grouped_games = games.groupby

In [180]:
grouped_games = games.groupby('team')

In [181]:
group = grouped_games.get_group('Arsenal')

In [182]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_num,opponent_num,time_hour,day_num,target
0,2022-08-05,20:00,Premier League,Matchweek 1,Fri,Away,W,2,0,Crystal Palace,...,1.0,0,0,2022,Arsenal,0,7,20,4,1
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,2,Leicester City,...,0.0,0,0,2022,Arsenal,1,11,15,5,1
2,2022-08-20,17:30,Premier League,Matchweek 3,Sat,Away,W,3,0,Bournemouth,...,0.0,0,0,2022,Arsenal,0,2,17,5,1
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2,1,Fulham,...,1.0,0,0,2022,Arsenal,1,9,17,5,1
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2,1,Aston Villa,...,1.0,0,0,2022,Arsenal,1,1,19,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2021-05-02,14:00,Premier League,Matchweek 34,Sun,Away,W,2,0,Newcastle Utd,...,1.0,0,0,2021,Arsenal,0,15,14,6,1
54,2021-05-09,19:00,Premier League,Matchweek 35,Sun,Home,W,3,1,West Brom,...,1.0,0,0,2021,Arsenal,1,22,19,6,1
55,2021-05-12,20:15,Premier League,Matchweek 36,Wed,Away,W,1,0,Chelsea,...,0.0,0,0,2021,Arsenal,0,6,20,2,1
56,2021-05-19,19:00,Premier League,Matchweek 37,Wed,Away,W,3,1,Crystal Palace,...,0.0,0,0,2021,Arsenal,0,7,19,2,1
57,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,2,0,Brighton,...,1.0,0,0,2021,Arsenal,1,4,16,6,1

In [183]:
def rol_averages(group, cols, new_cols):
    group = group.sort_values('date')
    rol_stats = group[cols].rolling(3, closed='left').mean() # take the current week out
    group[new_cols] = rol_stats
    group = group.dropna(subset=new_cols) # drop any missing value
    return group

In [184]:
cols = ['gf', 'ga', 'sh', 'sot', 'dist', 'fk', 'pk','pkatt']
new_cols = [f'{c}_rolling' for c in cols]

In [185]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [186]:
rol_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_num,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2,1,Sheffield Utd,...,6,1,2.000000,1.333333,8.000000,3.666667,14.633333,0.666667,0.000000,0.000000
7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0,1,Manchester City,...,5,0,1.666667,1.666667,5.666667,3.666667,15.366667,0.000000,0.000000,0.000000
9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0,1,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.566667,0.666667,0.000000,0.000000
11,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1,0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.566667,1.000000,0.000000,0.000000
13,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0,3,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,19.333333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44,2023-05-02,20:00,Premier League,Matchweek 34,Tue,Home,W,3,1,Chelsea,...,1,1,2.000000,3.000000,14.333333,4.000000,15.733333,0.333333,0.000000,0.333333
45,2023-05-07,16:30,Premier League,Matchweek 35,Sun,Away,W,2,0,Newcastle Utd,...,6,1,2.333333,2.666667,16.333333,5.333333,15.433333,0.333333,0.000000,0.000000
46,2023-05-14,16:30,Premier League,Matchweek 36,Sun,Home,L,0,3,Brighton,...,6,0,2.000000,1.666667,11.333333,5.666667,15.866667,0.333333,0.000000,0.000000
47,2023-05-20,17:30,Premier League,Matchweek 37,Sat,Away,L,0,1,Nott'ham Forest,...,5,0,1.666667,1.333333,13.333333,5.666667,15.333333,0.000000,0.000000,0.000000
48,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Home,W,5,0,Wolves,...,6,1,0.666667,1.333333,11.666667,3.666667,16.466667,0.000000,0.000000,0.000000

In [187]:
games_rolling = games.groupby('team').apply(lambda x: rol_averages(x, cols, new_cols)) # applying a function to each team

In [188]:
games_rolling

                                 date   time            comp         round  \
team
Arsenal                 6  2020-10-04  14:00  Premier League   Matchweek 4
                        7  2020-10-17  17:30  Premier League   Matchweek 5
                        9  2020-10-25  19:15  Premier League   Matchweek 6
                        11 2020-11-01  16:30  Premier League   Matchweek 7
                        13 2020-11-08  19:15  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 39 2023-04-29  15:00  Premier League  Matchweek 34
                        40 2023-05-06  15:00  Premier League  Matchweek 35
                        41 2023-05-13  15:00  Premier League  Matchweek 36
                        42 2023-05-20  15:00  Premier League  Matchweek 37
                        43 2023-05-28  16:30  Premier League  Matchweek 38

                            day venue result  gf  ga         opponent  ...  \
team                                                                   ...
Arsenal                 6   Sun  Home      W   2   1    Sheffield Utd  ...
                        7   Sat  Away      L   0   1  Manchester City  ...
                        9   Sun  Home      L   0   1   Leicester City  ...
                        11  Sun  Away      W   1   0   Manchester Utd  ...
                        13  Sun  Home      L   0   3      Aston Villa  ...
...                         ...   ...    ...  ..  ..              ...  ...
Wolverhampton Wanderers 39  Sat  Away      L   0   6         Brighton  ...
                        40  Sat  Home      W   1   0      Aston Villa  ...
                        41  Sat  Away      L   0   2   Manchester Utd  ...
                        42  Sat  Home      D   1   1          Everton  ...
                        43  Sun  Away      L   0   5          Arsenal  ...

                            day_num  target  gf_rolling  ga_rolling  \
team
Arsenal                 6         6       1    2.000000    1.333333
                        7         5       0    1.666667    1.666667
                        9         6       0    1.000000    1.666667
                        11        6       1    0.666667    1.000000
                        13        6       0    0.333333    0.666667
...                             ...     ...         ...         ...
Wolverhampton Wanderers 39        5       0    1.666667    0.666667
                        40        5       1    1.000000    2.666667
                        41        5       0    1.000000    2.000000
                        42        5       0    0.333333    2.666667
                        43        6       0    0.666667    1.000000

                           sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 6    8.000000    3.666667    14.633333   0.666667
                        7    5.666667    3.666667    15.366667   0.000000
                        9    7.000000    3.666667    16.566667   0.666667
                        11   9.666667    4.000000    16.566667   1.000000
                        13   9.666667    2.666667    19.333333   1.000000
...                               ...         ...          ...        ...
Wolverhampton Wanderers 39  11.666667    4.666667    18.700000   0.666667
                        40  11.333333    2.333333    18.800000   0.666667
                        41   8.000000    2.000000    17.766667   0.000000
                        42   7.000000    1.333333    15.600000   0.000000
                        43   8.000000    2.333333    15.333333   0.333333

                            pk_rolling  pkatt_rolling
team
Arsenal                 6     0.000000       0.000000
                        7     0.000000       0.000000
                        9     0.000000       0.000000
                        11    0.000000       0.000000
                        13    0.333333       0.333333
...                                ...            ...
Wolverhampton Wanderers 39    0.333333       0.333333
                        40    0.333333       0.333333
                        41    0.333333       0.333333
                        42    0.000000       0.000000
                        43    0.000000       0.000000

[2088 rows x 40 columns]

In [189]:
games_rolling = games_rolling.droplevel('team') # drop index level (team)

In [190]:
games_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_num,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2,1,Sheffield Utd,...,6,1,2.000000,1.333333,8.000000,3.666667,14.633333,0.666667,0.000000,0.000000
7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0,1,Manchester City,...,5,0,1.666667,1.666667,5.666667,3.666667,15.366667,0.000000,0.000000,0.000000
9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0,1,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.566667,0.666667,0.000000,0.000000
11,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1,0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.566667,1.000000,0.000000,0.000000
13,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0,3,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,19.333333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39,2023-04-29,15:00,Premier League,Matchweek 34,Sat,Away,L,0,6,Brighton,...,5,0,1.666667,0.666667,11.666667,4.666667,18.700000,0.666667,0.333333,0.333333
40,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,1,0,Aston Villa,...,5,1,1.000000,2.666667,11.333333,2.333333,18.800000,0.666667,0.333333,0.333333
41,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Away,L,0,2,Manchester Utd,...,5,0,1.000000,2.000000,8.000000,2.000000,17.766667,0.000000,0.333333,0.333333
42,2023-05-20,15:00,Premier League,Matchweek 37,Sat,Home,D,1,1,Everton,...,5,0,0.333333,2.666667,7.000000,1.333333,15.600000,0.000000,0.000000,0.000000
43,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,L,0,5,Arsenal,...,6,0,0.666667,1.000000,8.000000,2.333333,15.333333,0.333333,0.000000,0.000000

In [191]:
games_rolling.index = range(games_rolling.shape[0]) # assign new indices to have uniqe value for each index

In [192]:
games_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_num,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2,1,Sheffield Utd,...,6,1,2.000000,1.333333,8.000000,3.666667,14.633333,0.666667,0.000000,0.000000
1,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0,1,Manchester City,...,5,0,1.666667,1.666667,5.666667,3.666667,15.366667,0.000000,0.000000,0.000000
2,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0,1,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.566667,0.666667,0.000000,0.000000
3,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1,0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.566667,1.000000,0.000000,0.000000
4,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0,3,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,19.333333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2083,2023-04-29,15:00,Premier League,Matchweek 34,Sat,Away,L,0,6,Brighton,...,5,0,1.666667,0.666667,11.666667,4.666667,18.700000,0.666667,0.333333,0.333333
2084,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,1,0,Aston Villa,...,5,1,1.000000,2.666667,11.333333,2.333333,18.800000,0.666667,0.333333,0.333333
2085,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Away,L,0,2,Manchester Utd,...,5,0,1.000000,2.000000,8.000000,2.000000,17.766667,0.000000,0.333333,0.333333
2086,2023-05-20,15:00,Premier League,Matchweek 37,Sat,Home,D,1,1,Everton,...,5,0,0.333333,2.666667,7.000000,1.333333,15.600000,0.000000,0.000000,0.000000
2087,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,L,0,5,Arsenal,...,6,0,0.666667,1.000000,8.000000,2.333333,15.333333,0.333333,0.000000,0.000000

### Retrain The Model

In [193]:
def make_predictions(data, predictors):
    train = data[data['date'] < '2022-01-01']
    test = data[data['date'] > '2022-01-01']
    rfc.fit(train[predictors], train['target'])
    preds = rfc.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test['target'], predicted = preds), index=test.index)
    precision = precision_score(test['target'], preds)
    return combined, precision

In [194]:
combined, precision = make_predictions(games_rolling, predictors + new_cols)

In [195]:
precision

0.5474137931034483

In [196]:
combined

      actual  predicted
55         0          1
56         1          0
57         1          0
58         1          1
59         1          1
...      ...        ...
2083       0          0
2084       1          0
2085       0          0
2086       0          0
2087       0          0

[1028 rows x 2 columns]

In [197]:
combined = combined.merge(games_rolling[['date', 'team', 'opponent', 'result']], left_index=True, right_index=True)

In [198]:
combined

,actual,predicted,date,team,opponent,result
55,0,1,2022-01-23,Arsenal,Burnley,D
56,1,0,2022-02-10,Arsenal,Wolves,W
57,1,0,2022-02-19,Arsenal,Brentford,W
58,1,1,2022-02-24,Arsenal,Wolves,W
59,1,1,2022-03-06,Arsenal,Watford,W
...,...,...,...,...,...,...
2083,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L
2084,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W
2085,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L
2086,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D
2087,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L

In [199]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {
    'Brighton and Hove Albion': 'Brighton',
    'Manchester United': 'Manchester UTD',
    'Newcastle United' : 'Newcastle UTD',
    'Tottenham Hotspur' : 'Tottenham',
    'West Ham United' : 'West Ham',
    'Wolverhampton Wanderers': 'Wolves'
}
mapping = MissingDict(**map_values)

In [200]:
mapping['Arsenal']

'Arsenal'

In [201]:
mapping['West Ham United']

'West Ham'

In [202]:
combined['new_team'] = combined['team'].map(mapping)

In [203]:
combined

,actual,predicted,date,team,opponent,result,new_team
55,0,1,2022-01-23,Arsenal,Burnley,D,Arsenal
56,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal
57,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal
58,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal
59,1,1,2022-03-06,Arsenal,Watford,W,Arsenal
...,...,...,...,...,...,...,...
2083,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves
2084,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves
2085,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves
2086,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D,Wolves
2087,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L,Wolves

In [204]:
merged = combined.merge(combined, left_on=['date', 'new_team'], right_on=['date', 'opponent'])

In [205]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,1,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
1,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
2,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
3,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
4,1,1,2022-03-06,Arsenal,Watford,W,Arsenal,0,0,Watford,Arsenal,L,Watford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
784,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves,1,1,Brighton and Hove Albion,Wolves,W,Brighton
785,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,0,Aston Villa,Wolves,L,Aston Villa
786,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves,1,0,Manchester United,Wolves,W,Manchester UTD
787,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D,Wolves,0,0,Everton,Wolves,D,Everton
788,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L,Wolves,1,0,Arsenal,Wolves,W,Arsenal

In [206]:
merged[(merged['predicted_x'] == 1) & (merged['predicted_y'] == 0)] ['actual_x'].value_counts()

1    84
0    68
Name: actual_x, dtype: int64

In [207]:
84 / 152

0.5526315789473685